package com.opendragon.community.mapper;

import com.opendragon.community.model.TagClass;
import com.opendragon.community.model.TagClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TagClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    long countByExample(TagClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int deleteByExample(TagClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int insert(TagClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int insertSelective(TagClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    List<TagClass> selectByExampleWithRowbounds(TagClassExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    List<TagClass> selectByExample(TagClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    TagClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") TagClass record, @Param("example") TagClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int updateByExample(@Param("record") TagClass record, @Param("example") TagClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int updateByPrimaryKeySelective(TagClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_class
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    int updateByPrimaryKey(TagClass record);
}