package com.opendragon.community.model;

public class TagClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_class.id
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_class.name
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_class.id
     *
     * @return the value of tag_class.id
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_class.id
     *
     * @param id the value for tag_class.id
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_class.name
     *
     * @return the value of tag_class.name
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_class.name
     *
     * @param name the value for tag_class.name
     *
     * @mbg.generated Sat Aug 31 14:25:57 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}